### ISSUE TITLE
Proper JOB variable

### ISSUE THREAD

**Issue by krishnaavril** [ynput/ayon-houdini#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

<img width="2747" alt="image" src="https://github.com/user-attachments/assets/89f94d6b-db79-46ef-a4e2-dd5a73d46195">
when using $JOB in houdini, there is a extra "/" coming after the project name
currently : //avril/jobs/ads/LBS_DEV//sh_ayonusdpublishtest/

### Expected Behavior:

Expected : //avril/jobs/ads/**LBS_DEV/sh_ayonu**sdpublishtest/

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

using $JOB for any ayon project, see if you have any "//" in it

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by krishnaavril** [comment]
Just curioius, @MustafaJafar  @BigRoy Do you have the same issue too?

**Comment by BigRoy** [comment]
@krishnaavril just remove the `/` from the template and you'd be good, no?

**Comment by krishnaavril** [comment]
```just remove the / from the template and you'd be good, no?```

No it the next variable will not work as expected

I removed the {hierarchy}, and its good now, may I know what is this hierarchy and where can I find it?

**Comment by MustafaJafar** [comment]
Currently, I've this template. which exactly the same as the work template.
```
{root[work]}/{project[name]}/{hierarchy}/{folder[name]}/work/{task[name]}
```
and it evaluates to 
```
/ -> echo "`$JOB`"
//storage/work/ayon/RoboRangers_BeyondTheCircuit/Characters/Axel_Steelblade/work/modeling
```
```
>>> import os
>>> os.getenv("JOB")
'//storage/work/ayon/RoboRangers_BeyondTheCircuit/Characters/Axel_Steelblade/work/modeling'
`

**Comment by krishnaavril** [comment]
> So, I've figured out the issue by accident. 
> 
> @BigRoy @iLLiCiTiT where should we put this issue? 
> 
> ![image](https://github.com/user-attachments/assets/9c1597bc-14f9-4cb6-89dd-7f622565b613)
> 
> 

Yes exactly!

Heiarchy was not working, that what this ticket I raised...

**Comment by BigRoy** [comment]
> @BigRoy @iLLiCiTiT where should we put this issue?

So basically, if there is no parent `{hierarchy}` is an empty string `""`
But if there is a parent or multiples then `{hierarchy}` is `parent` or `parent/parent` or `parent/parent/parent` etc.
So in a way, what you're seeing is correct - whether that's useful in practice I guess is up for discussion.
This should be an issue on `ayon-core` if you want to discuss 'better ideas' because that logic lives [here](https://github.com/ynput/ayon-core/blob/e194652f65d122f769c028e3df5aca539f186018/client/ayon_core/pipeline/template_data.py#L88-L110).
One may argue that the value should, like "folder path" always be prefixed with a `/` so that no parent is `"/"` but with parents it is e.g. `/parent/parent`

---

Anyway, for now I'd recommend changing your template to: `{root[work]}/{project[name]}{folder[path]}/work/{task[name]}` which should resolve the issue?
