### ISSUE TITLE
AYON dependencies conflict with stock Houdini dependencies

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-houdini#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

`PIL` library provided by AYON is not compatible with Houdini.

Similar to other Python-version dependent dependencies this might need to become a runtime dependency, like ocio and otio with this PR https://github.com/ynput/OpenPype/pull/5206

### Expected Behavior:

The conflict should be resolved.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

I have no idea. will update it as soon as I know.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Additional context:

ported from internal backlog.
The issue was originally written in OP terms, I'm not sure if it still exists in ayon.
I didn't encounter the issue before. I'm not sure if addon split fixes the issue.

**Comment by BigRoy** [comment]
> I didn't encounter the issue before. I'm not sure if addon split fixes the issue.

As far as I know it's a Houdini 20+ issue for which a workaround has been to prepend to `PYTHONPATH` of the application environment Houdini's own Python libs.

For example:
```json
{
    "HOUDINI_VERSION": "20.0.724",
    "PYTHONPATH": [
        "C:/Program Files/Side Effects Software/Houdini {HOUDINI_VERSION}/python310/lib/site-packages",
        "{PYTHONPATH}"
    ]
}
```

**Comment by BigRoy** [comment]
Just referencing this OpenPype issue which seemed related as well: https://github.com/ynput/OpenPype/issues/5586

**Comment by MustafaJafar** [comment]
> Just referencing this OpenPype issue which seemed related as well: [ynput/OpenPype#5586](https://github.com/ynput/OpenPype/issues/5586)

It's not just related it's the same (internally). 

> As far as I know it's a Houdini 20+ issue for which a workaround has been to prepend to `PYTHONPATH` of the application environment Houdini's own Python libs.

Thanks for mentioning it here as well as in https://github.com/ynput/ayon-houdini/pull/3

I wonder should we code it in the addon ?
Because I think it's not good asking users to write some setting by default.

**Comment by BigRoy** [comment]
> I wonder should we code it in the addon ?
> Because I think it's not good asking users to write some setting by default.

It's debatable whether the workaround with prepending the path is even a 'good long term solution'. It's more of a hack that helps us out now instead of how it should be done. It may still have lurking issues in the long run, e.g. AYON's codebase expecting another version of PIL than Houdini - and hence doing calls against Houdini's PIL version that isn't API compatible with what AYON expect and thus, calls the wrong functions or wrong arguments, etc. I know @iLLiCiTiT doesn't like it - with good reason. :D

Also, having these paths 'auto-injected' may be non-trivial for any complex case where a studio is using heavily customized executable paths, e.g. custom Houdini install locations, or launches Houdini through `rez` or whatever - it may not be trivial from just the tool settings or the application envs to know the correct path to the Houdini python libs.

**Comment by iLLiCiTiT** [comment]
But PIL is in runtime dependencies. It is not added to `PYTHONPATH`. Question is if this is still relevant issue.

**Comment by antirotor** [comment]
Please re-open if it is still issue. Handling this in some reasonable way is somewhat complex task, definitely deserving its own issue.

> [!NOTE]
> Related https://github.com/ynput/ayon-core/issues/816
