### ISSUE TITLE
Load Asset LOP: Representation does not update when saving to another context

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-houdini#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When the AYON Load Asset LOP is set to load using e.g. folder path `$AYON_FOLDER_PATH` then upon change of that Houdini variable the 'parameter changed' callback does not seem to trigger for the HDA and thus the representation ID remains the old value - which seems counter-intuitive.

![image](https://github.com/ynput/ayon-houdini/assets/2439881/4ae07173-2682-43d4-8fdc-4221d6b90010)

### Expected Behavior:

On change of one of the variables, like `$AYON_FOLDER_PATH` preferably we're able to respond to that change and then re-evaluate the loaded representation id.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Load using Load Asset LOP
2. Save scene to another context.
3. Load asset lop is not updated to new context.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by MustafaJafar** [comment]
I think the source of the problem is the representation name.
we should update the representation name before calling `get_representation_id` 

https://github.com/ynput/ayon-houdini/blob/701d46ce94f79955519ff262f250369785a7ccc4/client/ayon_houdini/api/hda_utils.py#L281


![image](https://github.com/ynput/ayon-houdini/assets/20871534/7388c0a3-47c6-448e-81e9-d33d8a0183ec)

So, I have to change it manually, in order to continue the execution flow as expected.
![image](https://github.com/ynput/ayon-houdini/assets/20871534/406e0d04-7405-48c0-9958-7d6ccccddb84)

**Comment by BigRoy** [comment]
This will be fixed by https://github.com/ynput/ayon-houdini/pull/112 because the expressions will respond to the parameter value changes.
