### ISSUE TITLE
Houdini USD-rop is not publishing caches along

### ISSUE THREAD

**Issue by krishnaavril** [ynput/ayon-houdini#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

1. I published a geometry through USD from solaris, The output file of USD is point to "$HIP/pyblish/usdcamera.usd" (like shown in the attachment above)
2. after few version of publishes done successfully from ayon
3. I opened the latest version published usd(and some previous version) through USD tweak
4. They all referencing from same file in all the shots(basically this path $HIP/pyblish/usdcamera.usd)there is no version control, in all versions its loading same files

### Expected Behavior:

Houdini USD-rop should be publishing caches along and relinked properly.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

I'm attatching the sample Ayon project where I tested
https://drive.google.com/file/d/1W_MKsUrn9J36UmnfQXXa7IBA-OFVLXCQ/view?usp=sharing

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
> I got it working after flattening the stage/layer. 
> 
> Problem solved, none of the "SOP imports" are referencing but still publishes are referencing it

You closed this - and mentioned the comment I posted here elsewhere.

However, in that case the USD isn't referencing or sublayering those. However, it is in this case where you're _generating_ new data as one blob most likely the best way to go forward since you don't need that extra additional layer.

But **why did it generate a publish without remapping?**

This is because the publishing logic that "remaps" it _only_ remaps Explicit Layer Save paths. In this case, your scene file does not have the layer as an *explicit layer save path* but an **implicit layer save path**

![image](https://github.com/user-attachments/assets/3ece9d70-f535-4e26-a087-0964c52cb9b6)

If it were explicit, it should get picked up:

![image](https://github.com/user-attachments/assets/b1ff983d-4aa4-4fed-a35f-972b1b63a4cd)

![image](https://github.com/user-attachments/assets/9102c6e3-6e96-4a2e-9224-a76495a10c5b)
